"""
MCP Tools for Frida operations - UnionPay automation
"""

import os
from typing import Any, Dict, List, Optional
from mcp.server.fastmcp import FastMCP

from android_proxy_mcp.frida.rpc_client import UnionPayRPCClient

# Global client instance (lazy attach)
_frida_client: Optional[UnionPayRPCClient] = None
_script_path: str = os.path.abspath(os.path.join(
    os.path.dirname(__file__), '../../../frida-scripts/bypass-capture.js'
))


def register_frida_tools(mcp: FastMCP) -> None:
    """Register all Frida-related MCP tools"""

    @mcp.tool()
    def frida_status(package_name: str = "com.unionpay.android") -> Dict[str, Any]:
        """
        Check Frida connection status to the target app.
        Also verifies that the script is loaded correctly.
        
        Args:
            package_name: Target app package name (default: com.unionpay.android)
        """
        global _frida_client
        
        try:
            if _frida_client is None:
                _frida_client = UnionPayRPCClient(package_name)
                _frida_client.attach(_script_path)
            
            keys = _frida_client.get_captured_session_keys()
            
            return {
                "status": "connected",
                "package_name": package_name,
                "script_path": _script_path,
                "captured_keys_count": len(keys),
                "captured_keys": keys
            }
        except Exception as e:
            return {
                "status": "error",
                "error": str(e),
                "hint": "Make sure:\n1. Device is connected via USB\n2. Frida server is running on device\n3. Target app is running\n4. USB debugging is enabled"
            }

    @mcp.tool()
    def frida_get_session_keys() -> Dict[str, Any]:
        """
        Get all captured session keys from Frida.
        These are generated by UPNSACryptUtil::randomSessionKey when app starts/login.
        """
        global _frida_client
        
        if _frida_client is None:
            return {"error": "Frida not connected. Call frida_status first."}
        
        try:
            keys = _frida_client.get_captured_session_keys()
            return {
                "count": len(keys),
                "keys": keys
            }
        except Exception as e:
            return {"error": str(e)}

    @mcp.tool()
    def frida_decrypt(ciphertext: str) -> Dict[str, Any]:
        """
        Decrypt ciphertext using native app decryption via Frida RPC.
        Calls com.unionpay.utils.IJniInterface.d(ciphertext).
        
        Args:
            ciphertext: Hex-encoded ciphertext to decrypt
        """
        global _frida_client
        
        if _frida_client is None:
            return {"error": "Frida not connected. Call frida_status first."}
        
        try:
            plaintext = _frida_client.decrypt(ciphertext)
            if plaintext is None:
                return {
                    "error": "Decryption returned null",
                    "hint": "Check if ciphertext is valid hex, and IJniInterface is loaded"
                }
            return {
                "ciphertext": ciphertext,
                "plaintext": plaintext
            }
        except Exception as e:
            return {"error": str(e)}

    @mcp.tool()
    def frida_encrypt(plaintext: str) -> Dict[str, Any]:
        """
        Encrypt plaintext using native app encryption via Frida RPC.
        Calls com.unionpay.utils.IJniInterface.c(plaintext).
        
        Args:
            plaintext: Plaintext string to encrypt
        """
        global _frida_client
        
        if _frida_client is None:
            return {"error": "Frida not connected. Call frida_status first."}
        
        try:
            ciphertext = _frida_client.encrypt(plaintext)
            if ciphertext is None:
                return {
                    "error": "Encryption returned null",
                    "hint": "Check if IJniInterface is loaded"
                }
            return {
                "plaintext": plaintext,
                "ciphertext": ciphertext
            }
        except Exception as e:
            return {"error": str(e)}

    @mcp.tool()
    def frida_bypass() -> Dict[str, Any]:
        """
        Force apply Bangcle (梆梆) Frida detection bypass.
        This is normally done automatically on load, but can be called manually if needed.
        """
        global _frida_client
        
        if _frida_client is None:
            return {"error": "Frida not connected. Call frida_status first."}
        
        try:
            result = _frida_client.bypass()
            return {
                "success": result,
                "message": "Bypass applied. 5 detection points should be NOPed now."
            }
        except Exception as e:
            return {"error": str(e)}
